//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTracker.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketTracker.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {
        ///    font-size: 14px;
        ///    font-family: &quot;Calibri&quot;, sans-serif;
        ///}
        ///
        ///#greeting p {
        ///    font-size: 20px;
        ///    color: #0e2e47;
        ///}
        ///
        ///#regarding-request {
        ///    font-size: 18px;
        ///    color: #da383c;
        ///}
        ///
        ///#close {
        ///
        ///}
        ///
        ///#TimeSummary table {
        ///    width: 100%;
        ///}
        ///
        ///#TimeSummary th {
        ///    background-color: #a3a8aa;
        ///}
        ///        
        ///#TimeSummary table, #TimeSummary td, #TimeSummary th {
        ///    border-collapse: collapse;
        ///    border: 1px solid black;
        ///    text-align: left;
        ///}.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            font-size: 100%;
        ///            font-family: Gadugi;
        ///        }
        ///        
        ///        #TimeSummary table, #TimeSummary td, #TimeSummary th {
        ///            border-collapse: collapse;
        ///            border: 1px solid black;
        ///            text-align: left;
        ///        }
        ///        
        ///        #TimeSummary td, #TimeSummary th {
        ///            width: 200px;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketAbandonded {
            get {
                return ResourceManager.GetString("TicketAbandonded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        {txtStyle}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div id=&quot;greeting&quot;&gt;
        ///            &lt;p&gt;{lblFirstName}&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            I hope that you are having a wonderful day!
        ///        &lt;/p&gt;
        ///        &lt;p id=&quot;regarding-request&quot;&gt;
        ///            This email is regarding the following request: {lblTicketSubject}
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketComplete {
            get {
                return ResourceManager.GetString("TicketComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            font-size: 100%;
        ///            font-family: Gadugi;
        ///        }
        ///        
        ///        #TimeSummary table, #TimeSummary td, #TimeSummary th {
        ///            border-collapse: collapse;
        ///            border: 1px solid black;
        ///            text-align: left;
        ///        }
        ///        
        ///        #TimeSummary td, #TimeSummary th {
        ///            width: 200px;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketInProgress {
            get {
                return ResourceManager.GetString("TicketInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        {txtStyle}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div id=&quot;greeting&quot;&gt;
        ///            &lt;p&gt;{lblFirstName}&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            I hope that you are having a wonderful day!
        ///        &lt;/p&gt;
        ///        &lt;p id=&quot;regarding-request&quot;&gt;
        ///            This email is regarding the following request: {lblTicketSubject}
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketPriorityChanged {
            get {
                return ResourceManager.GetString("TicketPriorityChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        {txtStyle}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div id=&quot;greeting&quot;&gt;
        ///            &lt;p&gt;{lblFirstName}&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            I hope that you are having a wonderful day!
        ///        &lt;/p&gt;
        ///        &lt;p id=&quot;regarding-request&quot;&gt;
        ///            We have created a new ticket for the following request: {lblTicketSubject}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketReceipt {
            get {
                return ResourceManager.GetString("TicketReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        {txtStyle}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div id=&quot;greeting&quot;&gt;
        ///            &lt;p&gt;{lblFirstName}&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            I hope that you are having a wonderful day!
        ///        &lt;/p&gt;
        ///        &lt;p id=&quot;regarding-request&quot;&gt;
        ///            This email is regarding the following request: {lblTicketSubject}
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketTargetChanged {
            get {
                return ResourceManager.GetString("TicketTargetChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {
        ///			font-size: 14px;
        ///			font-family: &quot;Calibri&quot;, sans-serif;
        ///		}
        ///
        ///		#greeting p {
        ///			font-size: 20px;
        ///			color: #0e2e47;
        ///		}
        ///
        ///		#regarding-request {
        ///			font-size: 18px;
        ///			color: #da383c;
        ///		}
        ///
        ///		#close {
        ///
        ///		}
        ///
        ///		#TimeSummary table {
        ///			width: 100%;
        ///		}
        ///
        ///		#TimeSummary th {
        ///			background-color: #a3a8aa;
        ///		}
        ///
        ///		#TimeSummary tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeeklyEmail {
            get {
                return ResourceManager.GetString("WeeklyEmail", resourceCulture);
            }
        }
    }
}
